export const GET_INITIAL_STATE = 'GET_INITIAL_STATE';

export const SET_FORM_VALUES = 'SET_FORM_VALUES_R';

export const SUBMIT_FORMS_S = 'SUBMIT_FORMS_S';

export const ERROR_PASSWORD_MISMATCH = 'ERROR_PASSWORD_MISMATCH';

export const RESPONSE_REGISTER = 'RESPONSE_REGISTER';

export const RESPONSE_LOGIN = 'RESPONSE_LOGIN';

export const RESPONSE_INITIAL_STATE = 'RESPONSE_INITIAL_STATE';

export const RESPONSE_INITIAL_STATE_ERROR = 'RESPONSE_INITIAL_STATE_ERROR';

export const ERROR = 'ERROR';